-- MySQL Script generated by MySQL Workbench
-- Sun Dec  4 17:43:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`personas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`personas` (
  `id` INT NOT NULL,
  `tipo_documento` VARCHAR(45) NOT NULL,
  `documento` VARCHAR(45) NOT NULL,
  `nombre_completo` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NULL,
  `genero` BINARY(1) NULL,
  `estado` BINARY(1) NULL,
  `personascol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `` VARCHAR(45) NOT NULL,
  `usuarioscol` VARCHAR(45) NOT NULL,
  `personas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_personas_idx` (`personas_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_personas`
    FOREIGN KEY (`personas_id`)
    REFERENCES `mydb`.`personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`torre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`torre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`torre` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` BINARY(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`piso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`piso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`piso` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` BINARY(1) NOT NULL,
  `torre_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_piso_torre1_idx` (`torre_id` ASC) VISIBLE,
  CONSTRAINT `fk_piso_torre1`
    FOREIGN KEY (`torre_id`)
    REFERENCES `mydb`.`torre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`habitacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`habitacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`habitacion` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `precio` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `piso_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_habitacion_piso1_idx` (`piso_id` ASC) VISIBLE,
  CONSTRAINT `fk_habitacion_piso1`
    FOREIGN KEY (`piso_id`)
    REFERENCES `mydb`.`piso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`reserva` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reserva` (
  `id` INT NOT NULL,
  `fecha_ini` DATE NULL,
  `fecha_fin` DATE NULL,
  `descuento` DECIMAL(2) NULL,
  `valor_pago` INT NULL,
  `personas_id` INT NOT NULL,
  `habitacion_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reserva_personas1_idx` (`personas_id` ASC) VISIBLE,
  INDEX `fk_reserva_habitacion1_idx` (`habitacion_id` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_personas1`
    FOREIGN KEY (`personas_id`)
    REFERENCES `mydb`.`personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_habitacion1`
    FOREIGN KEY (`habitacion_id`)
    REFERENCES `mydb`.`habitacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
